server:
  port: 8855
spring:
  datasource:
    dynamic:
      primary: cart
  redis:
    cluster:
      nodes: 218.76.8.107:8001,218.76.8.107:8002,218.76.8.107:8003
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
      timeout: 3000ms # 连接超时时间（毫秒）
mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml

#zk配置
zk:
 curator:
   retryCount: 5 #重试次数
   elapsedTimeMs: 5000 #
   connectUrl: tlshop.com:2181 #zk地址
   sessionTimeOutMs: 60000 #会话超时时间
   connectionTimeOutMs: 5000 #连接超时时间

rocketmq:
  producer:
    send-message-timeout: 30000 #发送消息超时时间
    group: order-group
  tulingmall:
    scheduleTopic: order-status-check #定时任务
    cancelGroup: cancel-order #消费组业务逻辑,取消超时未支付订单
    transGroup: cart-delete #事务消息群组
    transTopic: order-cart #订单-购物车主题
    asyncOrderTopic: async-order #异步订单topic
    asyncOrderGroup: async-order-group #异步下单消息消费

feign:
  client:
    config:
      default:
        loggerLevel: full
        requestInterceptors:
          - com.tuling.tulingmall.feignapi.interceptor.HeaderInterceptor
        readTimeout: 3000
        connectTimeout: 3000